# Generated by Django 3.0.6 on 2020-05-21 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('course_title', models.CharField(max_length=256)),
                ('contact_hour', models.IntegerField()),
                ('credit_hour', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prerequisite', models.CharField(blank=True, max_length=10, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'All courses List',
            },
        ),
        migrations.CreateModel(
            name='SemesterSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Semester Selection',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TakenCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('section', models.CharField(max_length=5)),
                ('gpa', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile')),
                ('teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile')),
            ],
            options={
                'verbose_name_plural': 'Taken Courses',
                'ordering': ['course_code__semester', 'course_code'],
            },
        ),
        migrations.CreateModel(
            name='CompletedCouse8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=3, max_digits=5)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('section', models.CharField(max_length=5)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile')),
            ],
            options={
                'verbose_name_plural': 'Completed 8th sem courses',
            },
        ),
        migrations.CreateModel(
            name='CompletedCouse7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=3, max_digits=5)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('section', models.CharField(max_length=5)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile')),
            ],
            options={
                'verbose_name_plural': 'Completed 7th sem courses',
            },
        ),
        migrations.CreateModel(
            name='CompletedCouse6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=3, max_digits=5)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('section', models.CharField(max_length=5)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile')),
            ],
            options={
                'verbose_name_plural': 'Completed 6th sem courses',
            },
        ),
        migrations.CreateModel(
            name='CompletedCouse5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=3, max_digits=5)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('section', models.CharField(max_length=5)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile')),
            ],
            options={
                'verbose_name_plural': 'Completed 5th sem courses',
            },
        ),
        migrations.CreateModel(
            name='CompletedCouse4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=3, max_digits=5)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('section', models.CharField(max_length=5)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile')),
            ],
            options={
                'verbose_name_plural': 'Completed 4th sem courses',
            },
        ),
        migrations.CreateModel(
            name='CompletedCouse3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=3, max_digits=5)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('section', models.CharField(max_length=5)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile')),
            ],
            options={
                'verbose_name_plural': 'Completed 3rd sem courses',
            },
        ),
        migrations.CreateModel(
            name='CompletedCouse2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=3, max_digits=5)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('section', models.CharField(max_length=5)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile')),
            ],
            options={
                'verbose_name_plural': 'Completed 2nd sem courses',
            },
        ),
        migrations.CreateModel(
            name='CompletedCouse1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=3, max_digits=5)),
                ('section', models.CharField(max_length=5)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile')),
            ],
            options={
                'verbose_name_plural': 'Completed 1st sem courses',
            },
        ),
        migrations.CreateModel(
            name='ApplyingCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('section', models.CharField(blank=True, max_length=5, null=True)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile')),
                ('teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile')),
            ],
            options={
                'verbose_name_plural': 'Applying Courses',
                'ordering': ['course_code__semester', 'course_code', 'student_id'],
            },
        ),
    ]
