# Generated by Django 3.0.6 on 2020-05-21 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section4DM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile')),
                ('teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile')),
            ],
            options={
                'verbose_name_plural': '4DM',
            },
        ),
        migrations.CreateModel(
            name='Section4CM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile')),
                ('teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile')),
            ],
            options={
                'verbose_name_plural': '4CM',
            },
        ),
        migrations.CreateModel(
            name='Section4BM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile')),
                ('teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile')),
            ],
            options={
                'verbose_name_plural': '4BM',
            },
        ),
        migrations.CreateModel(
            name='Section4AM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile')),
                ('teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile')),
            ],
            options={
                'verbose_name_plural': '4AM',
            },
        ),
        migrations.CreateModel(
            name='Section3DM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile')),
                ('teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile')),
            ],
            options={
                'verbose_name_plural': '3DM',
            },
        ),
        migrations.CreateModel(
            name='Section3CM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile')),
                ('teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile')),
            ],
            options={
                'verbose_name_plural': '3CM',
            },
        ),
        migrations.CreateModel(
            name='Section3BM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile')),
                ('teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile')),
            ],
            options={
                'verbose_name_plural': '3BM',
            },
        ),
        migrations.CreateModel(
            name='Section3AM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile')),
                ('teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile')),
            ],
            options={
                'verbose_name_plural': '3AM',
            },
        ),
        migrations.CreateModel(
            name='Section2DM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile')),
                ('teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile')),
            ],
            options={
                'verbose_name_plural': '2DM',
            },
        ),
        migrations.CreateModel(
            name='Section2CM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile')),
                ('teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile')),
            ],
            options={
                'verbose_name_plural': '2CM',
            },
        ),
        migrations.CreateModel(
            name='Section2BM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile')),
                ('teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile')),
            ],
            options={
                'verbose_name_plural': '2BM',
            },
        ),
        migrations.CreateModel(
            name='Section2AM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile')),
                ('teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile')),
            ],
            options={
                'verbose_name_plural': '2AM',
            },
        ),
        migrations.CreateModel(
            name='Section1DM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile')),
                ('teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile')),
            ],
            options={
                'verbose_name_plural': '1DM',
            },
        ),
        migrations.CreateModel(
            name='Section1CM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile')),
                ('teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile')),
            ],
            options={
                'verbose_name_plural': '1CM',
            },
        ),
        migrations.CreateModel(
            name='Section1BM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile')),
                ('teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile')),
            ],
            options={
                'verbose_name_plural': '1BM',
            },
        ),
        migrations.CreateModel(
            name='Section1AM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile')),
                ('teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile')),
            ],
            options={
                'verbose_name_plural': '1AM',
            },
        ),
    ]
